import os

PROJECT_NAME = "interceptor-py"

AWS_ACCESS_KEY = os.environ["AWS_ACCESS_KEY"]
AWS_SECRET_KEY = os.environ["AWS_SECRET_KEY"]
AWS_ACCOUNT_ID = os.environ["AWS_ACCOUNT_ID"]
AWS_SESSION_TOKEN = os.environ["AWS_SESSION_TOKEN"]
AWS_REGION = os.environ["AWS_REGION"]
AWS_SQS_SERVICE_NAME = os.environ["AWS_SQS_SERVICE_NAME"]

QUEUE_NAME = os.environ["QUEUE_NAME"]

MYSQL_USER = os.environ["MYSQL_USER"]
MYSQL_PASSWORD = os.environ["MYSQL_PASSWORD"]
MYSQL_ROOT_PASSWORD = os.environ["MYSQL_ROOT_PASSWORD"]
MYSQL_HOST = os.environ["MYSQL_HOST"]
MYSQL_TCP_PORT = os.environ["MYSQL_TCP_PORT"]
MYSQL_DATABASE = os.environ["MYSQL_DATABASE"]

DATABASE_URI = (
    f"mysql+mysqldb://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}:"
    f"{MYSQL_TCP_PORT}/{MYSQL_DATABASE}"
)
