# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import fetcher_pb2 as fetcher__pb2
import grpc


class FetcherServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchTrades = channel.unary_unary(
            "/notcoolj.transaction.v1.FetcherService/FetchTrades",
            request_serializer=fetcher__pb2.FetchTradesRequest.SerializeToString,
            response_deserializer=fetcher__pb2.FetchTradesResponse.FromString,
        )
        self.StopFetchTrades = channel.unary_unary(
            "/notcoolj.transaction.v1.FetcherService/StopFetchTrades",
            request_serializer=fetcher__pb2.StopFetchTradesRequest.SerializeToString,
            response_deserializer=fetcher__pb2.StopFetchTradesResponse.FromString,
        )


class FetcherServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FetchTrades(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StopFetchTrades(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_FetcherServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "FetchTrades": grpc.unary_unary_rpc_method_handler(
            servicer.FetchTrades,
            request_deserializer=fetcher__pb2.FetchTradesRequest.FromString,
            response_serializer=fetcher__pb2.FetchTradesResponse.SerializeToString,
        ),
        "StopFetchTrades": grpc.unary_unary_rpc_method_handler(
            servicer.StopFetchTrades,
            request_deserializer=fetcher__pb2.StopFetchTradesRequest.FromString,
            response_serializer=fetcher__pb2.StopFetchTradesResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "notcoolj.transaction.v1.FetcherService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class FetcherService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FetchTrades(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/notcoolj.transaction.v1.FetcherService/FetchTrades",
            fetcher__pb2.FetchTradesRequest.SerializeToString,
            fetcher__pb2.FetchTradesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def StopFetchTrades(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/notcoolj.transaction.v1.FetcherService/StopFetchTrades",
            fetcher__pb2.StopFetchTradesRequest.SerializeToString,
            fetcher__pb2.StopFetchTradesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
