import os

PROJECT_NAME = "courier-py"

MONGO_URI = os.environ["MONGO_URI"]
MONGO_DATABASE = os.environ["MONGO_DATABASE"]
MONGO_COLLECTION = os.environ["MONGO_COLLECTION"]

AWS_ACCESS_KEY = os.environ["AWS_ACCESS_KEY"]
AWS_SECRET_KEY = os.environ["AWS_SECRET_KEY"]
AWS_ACCOUNT_ID = os.environ["AWS_ACCOUNT_ID"]
AWS_SESSION_TOKEN = os.environ["AWS_SESSION_TOKEN"]
AWS_REGION = os.environ["AWS_REGION"]
AWS_SQS_SERVICE_NAME = os.environ["AWS_SQS_SERVICE_NAME"]

QUEUE_NAME = os.environ["QUEUE_NAME"]
